# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
unsetopt beep extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/heikki/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

PATH=$PATH:~/script:~/.rbenv/bin:~/.gem/ruby/2.3.0/bin
alias l='ls'
alias lsl='ls -lahSr'
alias lst='ls -latr'

function figr {
    grep --color --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=vendor -ri "$*" .
}
function figrc {
    grep --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=vendor -ri "$*" .
}
function figra {
    grep --color -ri "$*" .
}
function invim {
    $* | gvim -c "set noautochdir" -
}
function d {
    pathToGoDown=''
    if [ $# -eq 0 ]
    then
        dirsToGoDown=1
    else
        dirsToGoDown=$1
    fi
    for (( i=1; i <= $dirsToGoDown; ++i ))
    do
        pathToGoDown=$pathToGoDown"../"
    done
    cd $pathToGoDown
    echo $PWD
}

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/heikki/.sdkman"
[[ -s "/home/heikki/.sdkman/bin/sdkman-init.sh" ]] && source "/home/heikki/.sdkman/bin/sdkman-init.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/heikki/progs/google-cloud/google-cloud-sdk/path.zsh.inc' ]; then . '/home/heikki/progs/google-cloud/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/heikki/progs/google-cloud/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/heikki/progs/google-cloud/google-cloud-sdk/completion.zsh.inc'; fi
eval "$(rbenv init -)"

export DENO_INSTALL="/home/heikki/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH="$PATH:/home/heikki/.composer/vendor/bin"
